name: mastodon_api
description: A Dart library for interacting with the Mastodon API.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  oauth2: ^2.0.3
  http: ^1.2.1
  meta: ^1.9.1
  crypto: ^3.0.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
